### ISSUE TITLE
Document dependencies

### ISSUE THREAD

**Issue by Piturnah** [DCoxshall/dylstatus#2]
There is an undocumented dependency on `psutil`. It seems based on your README 
> try this on your machine (not recommended)

that this project is for personal use/exploration and not intended for other users, so it is understandable if it's not worth it to document your dependencies. 

But it could be as simple as maintaining some [requirements.txt](https://pip.pypa.io/en/stable/reference/requirements-file-format/) in the root directory or otherwise, and comes with the following benefits:

- Lock your versions based on semver to avoid difficult-to-debug conflicts
- Easy to reinstall deps when running on a new machine
- New users don't have to manually work out what deps are missing

**Comment by DCoxshall** [comment]
Just like the #!/usr/bin/python thing, I also didn't know this existed. I'm researching it now and it looks like a good addition to the project but there's one thing I'm confused about - is there any easy way to know which versions of a given package might be in/compatible with a codebase? I could literally just have a requirements.txt that has nothing but `psutil` in it, but what if some older versions of psutil work and others don't?

**Comment by DCoxshall** [comment]
Actually, while I'm asking questions: where do I keep a note of the semantic version of the project? In the requirements.txt file?

**Comment by Piturnah** [comment]
If you run `$ pip freeze` it will give you a list of all the versions of all installed packages in your env. This is the version I had installed when I ran dylstatus:
```console
$ pip freeze | grep psutil
psutil==5.9.4
```
The implication here is that versions ^5.9 (and probably older but obviously you'd have to check) will work.

**Comment by DCoxshall** [comment]
I've added a simple requirements.txt, if there's anything wrong with it please let me know. Also, please let me know of any other suggestions you might have, because I really appreciate the issues you've brought to my attention. Thanks!
